name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PULL REPOSITORY
        uses: actions/checkout@v2

      - name: USING ACTION TO BUILD AND PUST :)
        uses: NRO04/docker-build-push-action@v2
        with: #args for action, all of them are required
          name-repository: 40781998/todo-frontend #repository name, specify what the repository will be called on dockerhub.
          tag: latest #tag for repository
          docker-username: 40781998 #${{ secrets.DOCKER_USERNAME }} # docker account - username
          docker-password: Paul@1234
      
